### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by paras06** [hoangddt/simple-Django-REST-API#3]
Hi, 

Your code is throwing below error when I executed the command - **python manage.py migrate**

TypeError: __init__() missing 1 required positional argument: 'on_delete'

Log Details--

C:\Project\simple-Django-REST-API>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Project\simple-Django-REST-API\snippets\models.py", line 14, in <module>
    class Snippet(models.Model):
  File "C:\Project\simple-Django-REST-API\snippets\models.py", line 21, in Snippet
    owner = models.ForeignKey('auth.User', related_name='snippets')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by hoangddt** [comment]
This project was created 4 years ago and at that time, on_delete is not a required argument.

Now, django have updated and it is required, to fix this, you can add `on_delete=models.CASCADE` as an extra argument.
Please change line 21 in `simple-Django-REST-API\snippets\models.py` from:
>owner = models.ForeignKey('auth.User', related_name='snippets')

to:
>owner = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE)

Then it should works
